apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: veritas_production_db
    url: postgres:5432
    database: veritas_db
    user: veritas_admin
    secureJsonData:
      password: veritas_secure_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
      timescaledb: false
      searchPath: 'marts,staging,raw,public'
    isDefault: true
    editable: true
    orgId: 1
