name: 'veritas_pipeline'
version: '1.0.0'
config-version: 2

profile: 'veritas_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  veritas_pipeline:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
    marts:
      +schema: marts
      +materialized: table
